# Generated by Django 4.2.5 on 2023-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
